# Generated by Django 3.1.7 on 2021-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='favorites',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='anime',
            name='members',
            field=models.CharField(max_length=50),
        ),
    ]
