# Generated by Django 3.1.7 on 2021-03-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_main', '0002_auto_20210306_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='favorites',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='members',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='popularity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='ranked',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
